# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interaction_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication,QMainWindow
from PyQt5 import uic
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1037, 793)
        self.rec_again = QtWidgets.QPushButton(Form)
        self.rec_again.setGeometry(QtCore.QRect(740, 590, 161, 61))
        self.rec_again.setObjectName("rec_again")
        self.number_gesture = QtWidgets.QPushButton(Form)
        self.number_gesture.setGeometry(QtCore.QRect(80, 370, 191, 71))
        self.number_gesture.setObjectName("number_gesture")
        self.letter_gesture = QtWidgets.QPushButton(Form)
        self.letter_gesture.setGeometry(QtCore.QRect(350, 370, 191, 71))
        self.letter_gesture.setObjectName("letter_gesture")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(620, 290, 91, 181))
        self.result_label.setObjectName("result_label")
        self.letter_rec = QtWidgets.QPushButton(Form)
        self.letter_rec.setGeometry(QtCore.QRect(80, 610, 191, 71))
        self.letter_rec.setObjectName("letter_rec")
        self.pattern_choise = QtWidgets.QLabel(Form)
        self.pattern_choise.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.pattern_choise.setObjectName("pattern_choise")
        self.explanation = QtWidgets.QLabel(Form)
        self.explanation.setGeometry(QtCore.QRect(20, 10, 1001, 321))
        self.explanation.setObjectName("explanation")
        self.number_rec = QtWidgets.QPushButton(Form)
        self.number_rec.setGeometry(QtCore.QRect(350, 490, 191, 71))
        self.number_rec.setObjectName("number_rec")
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(450, 700, 161, 61))
        self.close_button.setObjectName("close_button")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(690, 380, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.number_rec_2 = QtWidgets.QPushButton(Form)
        self.number_rec_2.setGeometry(QtCore.QRect(80, 490, 191, 71))
        self.number_rec_2.setObjectName("number_rec_2")

        self.retranslateUi(Form)
        self.close_button.clicked.connect(Form.close)
        self.rec_again.clicked.connect(self.textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Interaction"))
        self.rec_again.setText(_translate("Form", "清除历史"))
        self.number_gesture.setText(_translate("Form", "1.手写数字识别"))
        self.letter_gesture.setText(_translate("Form", "2.手写字母识别"))
        self.result_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">识别结果：</span></p><p><br/></p></body></html>"))
        self.letter_rec.setText(_translate("Form", "5.动态手势识别"))
        self.pattern_choise.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">模式选择：</span></p><p><span style=\" font-size:12pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.explanation.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">使用说明</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">本交互界面主要包括5个功能，包括静态手势（数字和字母）识别、动态手势识别、手写字体（数字和字母）识别。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">1.点击“手写数字识别”，得到手写数字识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">2.点击“手写字母识别”，得到手写字母识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">3.点击“数字手势识别”按钮，做出美国数字手语，得到识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">4.点击“字母手势识别”按钮，做出美国字母手语，得到识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">5.点击“动态手势识别”按钮，做出设定的&quot;Click&quot;,&quot;Stop&quot;,&quot;Rotate&quot;,&quot;No&quot;的手势，得到识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">6.点击“清除历史”，清除识别结果。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">7.点击“关闭界面”，界面关闭。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.number_rec.setText(_translate("Form", "4.字母手势识别"))
        self.close_button.setText(_translate("Form", "关闭界面"))
        self.number_rec_2.setText(_translate("Form", "3.数字手势识别"))
    def letter_rec(self):
        from .letter_rec import letter_rec
        letter_rec(self.ui)
    def number_rec(self):
        from .number_rec import number_rec
        number_rec(self.ui)
    def written_letter(self):
        from .written_letter import written_letter
        written_letter(self.ui)
    def written_number(self):
        from .written_number import written_number
        written_number(self.ui)
    # def speech(self):
    #     speech(self.ui)
    def letter_gesture(self):
        from .letter_gesture import letter_gesture
        letter_gesture(self.ui)
    def number_gesture(self):
        from .number_gesture import number_gesture
        number_gesture(self.ui)
    def dynamic_rec(self):
        from .dg_prediction_CSRN import CSRN
        CSRN(self.ui)
    def clear_log(self):
        self.ui.textBrowser.clear()
