name: gesture
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.22
  - scipy
  - scikit-learn>=1.1
  - scikit-image>=0.19
  - matplotlib>=3.7
  - pillow
  - pyqt=5.15
  - opencv
  - ffmpeg
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - cudnn
  - pip:
      - mediapipe==0.10.11
      - tensorflow==2.13.1
      - protobuf==3.20.3
      - pyttsx3==2.99
